# Comparación Estructuras de control con NumPy

Esta tanda de ejercicios trata de comparar la potencia de numpy para hacer muchas cosas en pocas líneas de código. 

El **objetivo** es hacer 2 versiones de cada ejercicio:

+ Primero usando estructuras de control, es decir, hacer lo que se pide usando un bucle para recorrer el array, sin usar funciones o métodos de numpy (o lo menos posible).
+ Posteriormente, hacer otra versión usando toda la potencia de numpy.


El primer ejercicio se da hecho como ejemplo.


## Para realizar estos ejercicios hay que ver antes el tema 1 hasta el final.

# Datos

Partimos de 4 ndarray:

+ Notas de matemáticas (tipo entero)
+ Notas de físicas (tipo entero)
+ Nombres de alumnos.
+ Array adicional de números reales.

In [92]:
import numpy as np

notas_mates = np.random.randint(0, 11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])
array_float = np.random.standard_normal(10)

print(notas_mates)
print(notas_fisica)


[10  9 10  5  5  1  2  2  8  5]
[ 0  9  5 10  5  0  7  0  5  5]


# 1. Obtener la suma de todas las notas de matemáticas 

Este se da hecho como ejemplo.

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

# Versión con estructuras de control
suma = 0
for elem in notas_mates:
    suma += elem
print(suma)

49


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

# Versión numpy
print(notas_mates.sum())

49


# Obtener la nota media de matemáticas

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

media=0
for i in notas_mates:
    media+=i

media/=len(notas_mates)
print(media)

4.1


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates.mean())

4.1


# Obtener un array con los nombres de los alumnos que han aprobado matemáticas

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

alumnos_mates=[]
for index,value in enumerate(notas_mates):
    if value>=5:
        alumnos_mates.append(alumnos[index])
array=np.array(alumnos_mates)
print(array)

[np.str_('Pedro'), np.str_('Antonio'), np.str_('Pablo'), np.str_('Carlos'), np.str_('Lucia')]
['Pedro' 'Antonio' 'Pablo' 'Carlos' 'Lucia']


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

print(alumnos[notas_mates >=5])

['Pedro' 'Antonio' 'Pablo' 'Carlos' 'Lucia']


# Obtener un array con los nombres de aquellos alumnos con nota mayor a la nota media de mates

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

alumnos_mates=[]
def media(ndarray):
    media=0
    for i in ndarray:
        media+=i
    media/=len(ndarray)
    return media

for index,value in enumerate(notas_mates):
    if value>media(notas_mates):
        alumnos_mates.append(alumnos[index])
array_mayor_media=np.array(alumnos_mates)
print(media(notas_mates))
print(array_mayor_media)

4.1
['Pedro' 'Antonio' 'Pablo' 'Carlos' 'Lucia']


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(np.mean(notas_mates))
print(alumnos[notas_mates > np.mean(notas_mates)])

4.1
['Pedro' 'Antonio' 'Pablo' 'Carlos' 'Lucia']


# Sumar 1 punto a aquellos alumnos que han suspendido mates (nota < 5)

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)

for index,value in enumerate(notas_mates):
    if value<5:
        notas_mates[index]+=1

print(notas_mates)

[2 7 7 2 5 7 8 2 2 2]
[3 7 7 3 5 7 8 3 3 3]


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
notas_mates[notas_mates<5]+=1
print(notas_mates)

[ 9  5  4  0  1  8  9  8  7 10]
[ 9  5  5  1  2  8  9  8  7 10]


# Sumar 2 punto a aquellos alumnos que han suspendido mates (nota < 5) y sumar 1 punto a los que han aprobado

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
for index,value in enumerate(notas_mates):
    if value<5:
        notas_mates[index]+=2
    elif value>=5:
        notas_mates[index]+=1
print(notas_mates)

[4 7 7 4 5 7 8 4 4 4]
[6 8 8 6 6 8 9 6 6 6]


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
notas_mates[notas_mates<5]+=2
notas_mates[notas_mates>=5]+=1
print(notas_mates)

[ 9  5  5  1  2  8  9  8  7 10]
[10  6  6  3  4  9 10  9  8 11]


# Generar un ndarray a partir de array_float
# Si el número es negativo, convertirlo a positivo

In [ ]:
import numpy as np
array_float = np.random.standard_normal(10)

print(array_float)
for index,value in enumerate(array_float):
    if value<0:
        array_float[index]*=-1
array2=np.array(array_float)
print(array2)

[ 0.69922601 -2.73681973  0.23314428 -1.25511496 -1.62251253 -0.05145463
 -1.09917332  0.31007899 -0.31174042  0.50269051]
[0.69922601 2.73681973 0.23314428 1.25511496 1.62251253 0.05145463
 1.09917332 0.31007899 0.31174042 0.50269051]


In [ ]:
import numpy as np
array_float = np.random.standard_normal(10)

print(array_float)
array2=np.abs(array_float)
print(array2)

[-0.2779424  -0.48260912  1.20092046  0.36890141  0.02987178  0.15387286
 -0.0696227   0.79457613 -0.51985582  1.12655135]
[0.2779424  0.48260912 1.20092046 0.36890141 0.02987178 0.15387286
 0.0696227  0.79457613 0.51985582 1.12655135]


# Poner un 10  en mates al alumno Pedro

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

for index,value in enumerate(alumnos):
    if value=="Pedro":
        notas_mates[index]=10

print(alumnos)
print(notas_mates)

['Juan' 'Pedro' 'Antonio' 'Maria' 'Pablo' 'Carlos' 'Lucia' 'Marta'
 'Noelia' 'Samuel']
[ 0 10  7  5  7  7 10  6  5  4]


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(alumnos)
print(notas_mates)
notas_mates[alumnos=="Pedro"]=10
print(notas_mates)

['Juan' 'Pedro' 'Antonio' 'Maria' 'Pablo' 'Carlos' 'Lucia' 'Marta'
 'Noelia' 'Samuel']
[10  5  8  5  3  8  3 10  8  9]
[10 10  8  5  3  8  3 10  8  9]


# Elevar al cuadrado todas las notas de matemáticas

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
for index,value in enumerate(notas_mates):
        notas_mates[index]**=2
print(notas_mates)

[10 10  8  5  9  8  9 10  8  9]
[100 100  64  25  81  64  81 100  64  81]


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
print(np.square(notas_mates))

[10000  2401  6561     0    81     0   256    81  2401 10000]
[100  49  81   0   9   0  16   9  49 100]


# Elevar al cuadrado las notas menores a 5 de matemáticas

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
for index,value in enumerate(notas_mates):
        if(value<5):
            notas_mates[index]**=2
print(notas_mates)

In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)

print(notas_mates)
notas_mates[notas_mates<5]**=2
print(notas_mates)

[ 0  3  7 10  4  8  5  5  7  6]
[ 0  9  7 10 16  8  5  5  7  6]


# Generar un ndarray que guarde el signo del array array_float. 

El signo se marca con lo siguiente:
+ -1 Si el signo es negativo
+ 0 si el número es 0
+ 1 si el signo es positivo

In [94]:
import numpy as np
array_float = np.random.standard_normal(10)

array_signo=[]

for i in array_float:
    if i==0:
        array_signo.append(0)
    elif i<0:
        array_signo.append(-1)
    else:
        array_signo.append(1)

print(array_float)
print(array_signo)

[-0.99130716  1.44482492  0.16637486 -1.66926333 -1.21234331 -0.87681116
  1.6987811   1.90296718  0.18737641  1.08222498]
[-1, 1, 1, -1, -1, -1, 1, 1, 1, 1]


In [95]:
import numpy as np
array_float = np.random.standard_normal(10)

print(array_float)
print(np.sign(array_float))

[ 1.4812868  -0.30281036 -0.32768641  1.89181985 -0.03590304 -0.2989522
 -1.41258213 -0.16119457 -1.03618069  0.65426864]
[ 1. -1. -1.  1. -1. -1. -1. -1. -1.  1.]


# Generar un ndarray que guarde la nota mínima de cada alumno entre mates y física

In [98]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

notas_minimas=[]
for index,_ in enumerate(alumnos):
    nota_mates=notas_mates[index]
    nota_fisica=notas_fisica[index]

    if nota_mates<=nota_fisica:
        notas_minimas.append(nota_mates)
    else: 
        notas_minimas.append(nota_fisica)

print(notas_mates)
print(notas_fisica)
print(np.array(notas_minimas))

[ 9  4  9  4  3  8  8  2 10  5]
[ 8  2  9  4  5 10  3  6  4  4]
[8 2 9 4 3 8 3 2 4 4]


In [ ]:
import numpy as np
notas_mates = np.random.randint(0, 11, 10)
notas_fisica = np.random.randint(0, 11, 10)
alumnos = np.array(["Juan", "Pedro", "Antonio", "Maria", "Pablo", "Carlos", "Lucia", "Marta", "Noelia", "Samuel"])

print(notas_mates)
print(notas_fisica)
print(np.fmin(notas_mates, notas_fisica))
#print(np.minimum(notas_mates, notas_fisica))

[10  2  7  2  8  7  6  6  2  9]
[ 6  9  7  0  4 10  6  1  2 10]
[6 2 7 0 4 7 6 1 2 9]
[6 2 7 0 4 7 6 1 2 9]


# Comprobar si alguien tiene un 10 matemáticas

In [ ]:
import numpy as np


In [ ]:
import numpy as np


# Comprobar si todos han aprobado física

In [ ]:
import numpy as np


In [ ]:
import numpy as np


# Generar un array de nombres de quienes han aprobado mates y física

In [ ]:
import numpy as np


In [ ]:
import numpy as np


# Generar un array de nombres de quien ha aprobado mates pero no física

In [ ]:
import numpy as np


In [ ]:
import numpy as np
