# Array de datos inicial

Disponemos de 2 arrays de datos:

+ ndarray de nombres
+ ndarray de notas

Los arrays tienen el mismo tamaño y se relacionan por su índice. "Alberto" ocupta el índice 0, su nota corresponde al índice 0.


Para hacer estos ejercicios hay que avanzar en el **Tema 1 hasta la página 24**

Estos ejercicios se realizan invocando funcionalidades de numpy, por lo que cada acción que se pide se realiza en una o dos líneas de código, sin utilizar estructuras de control

In [1]:
import numpy as np

nombres = np.array(["Alberto", "Álvaro", "Antonio", "Guillermo", "José Manuel", "Juan Diego", "Juan Ignacio",
                    "Juan José", "María", "Raúl", "Victor"])
print(nombres)
notas = np.random.randint(1, 11, nombres.size)
print(notas)

['Alberto' 'Álvaro' 'Antonio' 'Guillermo' 'José Manuel' 'Juan Diego'
 'Juan Ignacio' 'Juan José' 'María' 'Raúl' 'Victor']
[ 2  7  7 10  8  5  5  6  7  1  3]


# Métodos del ndarray, funciones de numpy y slicing

Realiza lo que se pide en cada comentario usando un método del propio objeto ndarray, función directa de numpy o el slice igual que en listas.



In [15]:
import numpy

nombres = numpy.array(["Alberto", "Álvaro", "Antonio", "Guillermo", "José Manuel", "Juan Diego", "Juan Ignacio",
                    "Juan José", "María", "Raúl", "Victor"])
notas = numpy.random.randint(1, 11, nombres.size)

# Muestra Nota media de los alumnos
media = numpy.mean(notas)
print(f"la nota media es {round(media,2)}")

# Muestra Desviación estándar
desv=numpy.std(notas)
print(f"la desviacion estandar es {round(desv,2)}")
# Mostrar nombres del revés mediante una slice
print(f"nombres al reves: {nombres[::-1]}")

# Ordenar, haciendo una copia de datos en otra variable, las notas de menor a mayor
notas_ord=numpy.sort(notas)
print(notas_ord)


la nota media es 6.64
la desviacion estandar es 2.27
nombres al reves: ['Victor' 'Raúl' 'María' 'Juan José' 'Juan Ignacio' 'Juan Diego'
 'José Manuel' 'Guillermo' 'Antonio' 'Álvaro' 'Alberto']
[ 3  4  4  5  6  7  8  8  9  9 10]


# Aritmética, Comparaciones e indexación booleana

Estos ejercicios requieren alguna comparación de arrays, indexación booleana y aritmética, además de alguna función o método de numpy. Si no controlas la indexación booleana busca antes en los apuntes y realiza tus propias pruebas hasta controlar cómo funcionan.

In [74]:
import numpy

nombres = numpy.array(["Alberto", "Álvaro", "Antonio", "Guillermo", "José Manuel", "Juan Diego", "Juan Ignacio",
                    "Juan José", "María", "Raúl", "Victor"])
notas = numpy.random.randint(1, 11, nombres.size)

print("1-Sumar 1 a todas las notas")
print(notas)
notas=numpy.add(notas,1)
print(notas)
print()

print("2-Mostrar cuantos aprobados hay")
aprobados= notas>=5
print(f"Hay {len(nombres[aprobados])} aprobados")
print()

print("Mostrar nombres de alumnos aprobados")
aprobados= notas>=5
print(nombres[aprobados])
print()


print("Mostrar nombres con nota superior a la media")
media = numpy.mean(notas)
print(f"{nombres[notas>media]} tienen nota superior a la media")
print()

print("Asignar un 5 a los que tienen un 4")
cuatros=notas==4
print(notas)
notas[cuatros]=5
print(notas)
print()

print("Sumar 1 a todas las notas mayores a 4")
mayor_que_cuatro=notas>4
print(notas)
notas[mayor_que_cuatro]+=1
print(notas)
print()

1-Sumar 1 a todas las notas
[ 5  1  7  2  4  4  5  8  5 10  3]
[ 6  2  8  3  5  5  6  9  6 11  4]

2-Mostrar cuantos aprobados hay
Hay 8 aprobados

Mostrar nombres de alumnos aprobados
['Alberto' 'Antonio' 'José Manuel' 'Juan Diego' 'Juan Ignacio' 'Juan José'
 'María' 'Raúl']

Mostrar nombres con nota superior a la media
['Alberto' 'Antonio' 'Juan Ignacio' 'Juan José' 'María' 'Raúl'] tienen nota superior a la media

Asignar un 5 a los que tienen un 4
[ 6  2  8  3  5  5  6  9  6 11  4]
[ 6  2  8  3  5  5  6  9  6 11  5]

Sumar 1 a todas las notas mayores a 4
[ 6  2  8  3  5  5  6  9  6 11  5]
[ 7  2  9  3  6  6  7 10  7 12  6]

