# Ejercicios con while

Vuelve a realizar los 4 ejercicios de **"Numpy 1"** utilizando un bucle **while** en lugar de for.

In [ ]:
# Ejercicio 1
import numpy as np

# Lista para crear el array a partir de ella
lista = [4.5, 7.36, 7., 0.56]

# Creamos el array mediante la estructura lista
mi_array = np.array(lista)

#Sigue a partir de aquí
print(f"Dimensiones: {mi_array.ndim}")
print(f"Tamaño: {mi_array.size}")
print(f"Shape: {mi_array.shape}")
print(f"Tipo: {mi_array.dtype}")

index=0
while index<len(mi_array):
    print(mi_array[index])
    index+=1


Dimensiones: 1
Tamaño: 4
Shape: (4,)
Tipo: float64
4.5
7.36
7.0
0.56


In [2]:
import numpy as np

def inicializar_array(ndarray):
    cont=0
    while cont <len(ndarray):
        valor=int(input("introduce un numero: "))
        ndarray[cont]=valor
        cont+=1
    return ndarray

array=np.array([1,2,3,4,6,8,10])
print(array)
print(array.dtype)
array_mod=inicializar_array(array)
print(array_mod)
print(array.dtype)


[ 1  2  3  4  6  8 10]
int64
[9 8 7 6 5 4 3]
int64


In [4]:
# Ejercicio 3
import numpy as np

def media(ndarray):
    media=0
    cont=0
    while cont <len(ndarray):
        media+=ndarray[cont]
        cont+=1
    media/=len(ndarray)
    return media

def minimo(ndarray):
    min=ndarray[0]
    cont=0
    while cont <len(ndarray):
        if ndarray[cont]<min:
            min=ndarray[cont]
        cont+=1
    return min

def maximo(ndarray):
    max=ndarray[0]
    cont=0
    while cont <len(ndarray):
        if ndarray[cont]>max:
            max=ndarray[cont]
        cont+=1
    return max
    
array=np.array([1,2,3,4,5])
print(media(array))
print(maximo(array))
print(minimo(array))

3.0
5
1


In [6]:
# Ejercicio 4
import numpy as np

def encontrar(array,valor):
    cont=0
    while cont <len(array):
        if array[cont]==valor:
            return cont
        cont+=1
        #no he puesto else por que retorna None si no encuentra nada
        
    
array=np.array([1,2,3,4,5])
valor=4

print(encontrar(array,valor))


3


### Ejercicio 5

Crear una función “desviación estándar” que reciba por parámetro un array y devuelva la desviación estándar. Calcular paso a paso el resultado utilizando un **for** para recorrer el array. También se debe usar la función “media” del ejercicio 2. Para calcular la raíz cuadrada podemos usar la función de numpy.sqrt(n). Operador potencia es **

In [ ]:
import numpy

def media(ndarray):
    suma = 0.0
    for i in ndarray:
        suma += i
    suma /= len(ndarray)
    return suma

def desviacion_estandar(array):
    m = media(array)
    suma_cuadrados = 0.0
    for x in array:
        suma_cuadrados += (x - m) ** 2
    varianza = suma_cuadrados / len(array)
    return numpy.sqrt(varianza)

array = numpy.array([1,2,3,4,5])
print(round(desviacion_estandar(array),2))
print(round(numpy.std(array),2))


1.41
1.41


# A partir de aquí puedes usar las funciones de NumPy de las diapositivas, además de bucles o las funciones creadas en ejercicios anteriores.

### Ejercicio 6 

Crea una función reciba por parámetro un array y un valor y devuelva cuantas veces aparece ese valor en el array.


In [18]:
import numpy

def recuento_apariciones(array,valor):
    result=numpy.where(array==valor)
    return(result)

array1=np.array([1,2,3,4,5,8,10,15,20,2,4,2])
valor=2
recuento=recuento_apariciones(array1,valor)

print(f"el valor {valor} aparece {len(recuento[0])} veces.")
# print(recuento)
# print(len(recuento[0]))

el valor 2 aparece 3 veces.


### Ejercicio 7

Crea una función que reciba por parámetro un array y devuelva cuantas veces aparece el valor máximo en el array.


In [22]:
import numpy

def recuento_maximos(array):
    max=numpy.max(array)
    result=numpy.where(array==max)
    return result


array1=numpy.array([1,2,3,4,5,8,10,15,20,2,4,2])
recuento=recuento_maximos(array1)

print(f"el valor maximo que es:{numpy.max(array1)} aparece {len(recuento[0])} veces.")

el valor maximo que es:20 aparece 1 veces.


### Ejercicio 8

Crea una función que reciba por parámetro un array y devuelva la moda.

In [ ]:
import numpy

def moda(array):
    array_unique, cont = numpy.unique(array, return_counts=True)
    moda = array_unique[numpy.argmax(cont)]  
    return moda

array1=numpy.array([1,2,3,4,5,8,10,15,20,2,4,2])
print(moda(array1))

[ 1  2  3  4  5  8 10 15 20]
[1 3 1 2 1 1 1 1 1]
2


### Ejercicio 9

Crea una función que reciba por parámetro un array y devuelva otro array que contenga los índices (posiciones del array original) de aquellos valores que son mayores a la media del array.

In [29]:
import numpy

def recuento_mayor_media(array):
    media=numpy.mean(array)
    result=numpy.where(array>media)
    return result


array1=numpy.array([1,2,3,4,5,8,10,15,20,2,4,2])
array_mayor_medias=recuento_mayor_media(array1)[0]
print(numpy.mean(array1))
print(array_mayor_medias)



6.333333333333333
[5 6 7 8]
