# Completa cada celda de código según el comentario.

No es necesario realizar funciones.

Realiza cada operación teniendo en cuenta todo el potencial de numpy y sus métodos.

In [2]:
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

In [2]:
# Muestra los atributos de array1 (dimensiones, tipo, tamaño, tamaño por dimensión o shape)
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

print(f"Dimensiones: {array1.ndim}")
print(f"Tipo: {array1.dtype}")
print(f"Tamaño: {array1.size}")
print(f"Shape: {array1.shape}")


Dimensiones: 1
Tipo: int64
Tamaño: 11
Shape: (11,)


In [ ]:
# Crea un array2 del mismo tamaño que array1 con todos a 1
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

array2=np.ones_like(array1)
print(array1)
print(array2)


[  2   5   4   2  49  34  59  21  45   6 105]
[1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
# Suma ambos arrays de forma vectorizada y guarda el resultado en array3
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

array2=np.ones_like(array1)
array3=array1+array2
print(array3)

[  3   6   5   3  50  35  60  22  46   7 106]


In [ ]:
# Genera un array booleano (array_bool) que indique que posiciones de array1 son mayores a 30. 
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

array_bool=array1>30
# Imprime array_bool para comprobar 
print(array_bool)

[False False False False  True  True  True False  True False  True]


In [ ]:
# A partir de array_bool, muestra por pantalla los valores que cumplen la condición (>40)
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

array_bool=array1>40
print(array1[array_bool])

[ 49  59  45 105]


In [ ]:
# Comprueba (imprime 1 True o False) si existe algún valor múltiplo de 7 en array1
import numpy as np
array1 = np.array([2, 5, 4, 2, 48, 34, 59, 22, 45, 6, 107])

print(np.any(array1%7==0))

False


In [ ]:
# Devuelve un array con todos los números menores a 40 o múltiplo de 7
import numpy as np
array1 = np.array([2, 7, 14, 2, 49, 34, 59, 21, 45, 6, 105])

condicion = (array1<40) | (array1%7==0)
array2=array1[condicion]
print(array2)

[  2   7  14   2  49  34  21   6 105]


In [ ]:
# Devuelve un array con todos los números menores a 40 que sean múltiplo de 7
import numpy as np
array1 = np.array([2, 7, 14, 2, 49, 34, 59, 21, 45, 6, 105])

condicion = (array1<40) & (array1%7==0)
array2=array1[condicion]
print(array2)

[21]


In [ ]:
# Multiplica y muestra todos los valores de array1
import numpy as np
array1 = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])

print(array1*3)

[  6  15  12   6 147 102 177  63 135  18 315]


---
# Notas y alumnos

La celda inferior contiene los datos **"notas"** y **"alumnos"** para realizar las siguientes.

In [34]:
# Array notas
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
print(notas)

# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])
print(alumnos)

[8 5 4 6 8 7 9 9 3 5 7 7 3 4 8]
['Pedro' 'Juan' 'Maria' 'Alfonso' 'Mario' 'Juana' 'Antonio' 'Marco'
 'Julia' 'Noelia' 'Alvaro' 'Natalia' 'Jose' 'Carlos' 'Diego']


In [35]:
# Muestra el valor medio y mediano de notas
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])

media=np.mean(notas)
print(media)
mediana=np.median(notas)
print(mediana)


6.2
7.0


In [38]:
# ¿Cuál es la desviación estándar y la varianza del conjunto de datos?
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])

desviacion=np.std(notas)
print("%.2f" %desviacion)
varianza=np.var(notas)
print("%.2f" %varianza)

2.01
4.03


In [39]:
# Calcula la desviación estándar a través de la varianza
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])

varianza=np.var(notas)
desviacion=np.sqrt(varianza)
print("%.2f" %desviacion)

2.01


In [40]:
# Comprueba si ha suspendido algún alumno
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])

print(np.any(notas<5))

True


In [44]:
# Muestra cuánntos alumnos han aprobado y cuantos han suspendido
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])

print(f"aprobados: {alumnos[notas>=5]}")
print(f"suspendidos: {alumnos[notas<5]}")

aprobados: ['Pedro' 'Juan' 'Alfonso' 'Mario' 'Juana' 'Antonio' 'Marco' 'Noelia'
 'Alvaro' 'Natalia' 'Diego']
suspendidos: ['Maria' 'Julia' 'Jose' 'Carlos']


# Percentil

https://es.wikipedia.org/wiki/Percentil

En el enlace de wikipedia se explica en qué consiste la medida percentil. Existen en numpy unos métodos para calcularlo.

In [ ]:
# ¿Qué valor se encuentra en el percentil 25? ¿y en el 50? ¿con qué valor coincide este último?
# Busca numpy.percentile en la documentación oficial


In [ ]:
# Vamos a filtrar a los alumnos
# Queremos solamente un 30% de los alumnos, los que tienen mejores notas. Calcula el valor del percentil correspondiente
import numpy as np
notas = np.array([8, 5, 4, 6, 8, 7, 9, 9, 3, 5, 7, 7, 3, 4, 8])
# Array alumnos
alumnos = np.array(["Pedro", "Juan", "Maria", "Alfonso", "Mario", "Juana", "Antonio", "Marco", 
                    "Julia", "Noelia", "Alvaro", "Natalia", "Jose", "Carlos", "Diego"])
# Muestra los nombres del 30% de alumnos con mejor nota
mejores_alumnos = alumnos[notas >= np.percentile(notas,70)]
print(f"El 30% de los alumnos con mejor nota son{mejores_alumnos}")



El 30% de los alumnos con mejor nota son['Pedro' 'Mario' 'Antonio' 'Marco' 'Diego']


In [6]:
# Comprueba el resultado anterior mostrando las notas de cada alumno
for index,alumno in enumerate(alumnos):
    print(f"alumno: {alumno} Nota: {notas[index]}")

alumno: Pedro Nota: 8
alumno: Juan Nota: 5
alumno: Maria Nota: 4
alumno: Alfonso Nota: 6
alumno: Mario Nota: 8
alumno: Juana Nota: 7
alumno: Antonio Nota: 9
alumno: Marco Nota: 9
alumno: Julia Nota: 3
alumno: Noelia Nota: 5
alumno: Alvaro Nota: 7
alumno: Natalia Nota: 7
alumno: Jose Nota: 3
alumno: Carlos Nota: 4
alumno: Diego Nota: 8
